replicaCount: 4

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

web:
  indexHtml: |
    <html>
      <head><title>My Test Page</title></head>
      <body>
        <h1>Hello from Helm + ArgoCD!</h1>
      </body>
    </html>
